// Generates human-readable user IDs like "Vivian_Hurley_1714400000000_042"
// Counter allows up to 1,000 unique IDs per millisecond.

let counter = 0;

const firstNames = [
  "Vivian", "Van", "Aitana", "Franklin", "Bridget", "Marshall", "Queen", "Zachary",
  "Alexis", "Major", "Lorelei", "Raphael", "Emersyn", "Easton", "Anika", "Raymond",
  "Madeleine", "Tatum", "Rachel", "Fletcher", "Esperanza", "Jeffery", "Haylee", "Stefan",
  "Emberly", "Kristian", "Hayden", "Kace", "Calliope", "Everest", "Anais", "Azariah",
  "Ariyah", "Joel", "Kelsey", "Kyng", "Sadie", "Amir", "Isabela", "Julius", "Louis",
  "Sasha", "Ben", "Arabella", "Ari", "Miriam", "Ares", "Avery", "Kenji", "Monroe",
  "Joziah", "Amaya", "Jeremy", "Alejandra", "Armando", "Brinley", "Harvey", "Lyla",
  "Dash", "Bristol", "Vance", "Teagan", "Frederick", "Penny", "Dean", "Demi", "Gideon",
  "Promise", "Maximilian", "Araceli", "Bryce", "Mckinley", "Colten", "Stormi", "Bradley",
  "Karen", "Ellie", "Jett", "Cataleya", "Bode", "Cassandra", "Adonis", "Elyse", "Brady",
  "Maya", "Myles", "Saylor", "Gabriel", "Elina", "Hezekiah", "Kora", "Axel", "Amani",
  "Malachi", "Ramona", "Carmelo", "Morgan", "Hayes", "Lena", "Adam", "Kaisley", "Augustus",
  "Aubree", "Kellen", "Aylin", "Emory", "Kaliyah", "Jenesis", "Graham", "Kassidy",
  "Lionel", "Zoya", "Mordechai", "Mia", "Jasper", "Naomi", "Shepard", "Elliot", "Kade",
  "Vienna", "Colt", "Ariya", "Sincere", "Priscilla", "Rio", "Legacy", "Francis", "Martha",
  "Julian", "Brylee", "Daxton", "Hadley", "Alessandro", "Jude", "Lara", "Houston",
  "Liliana", "Emma", "Nixon", "Kyra", "Weston", "London", "Tyler", "Lillie", "Sylas",
  "Luella", "Malakai", "Davina", "Alaina", "Julissa", "Wells", "Joelle", "Moses", "Nalani",
  "Gage", "Selena", "Javier", "Kaylee", "Andrea", "Rodrigo", "Zayne", "Emani", "Leonard",
  "Hunter", "Gustavo", "Bonnie", "Apollo", "Amara", "Rhett", "River", "Turner", "Collins",
  "Donovan", "Amora", "Landon", "Makayla", "Luciano", "Wrenley", "Benicio", "Lilliana",
  "Helen", "Sonny", "Kendall", "Patrick", "Caroline", "Giovanni", "Everleigh", "Dior",
  "Rosalie", "Nasir", "Romina", "Killian", "Moshe", "Ainsley", "Callum", "Charlotte",
  "Sebastian", "Kendra", "Juelz", "Harmoni", "Cade", "Adalynn", "Livia", "Mohamed",
  "Callie", "Marlon", "Margo", "Brock", "Navy", "Issac", "Briana", "Alberto", "Elsie",
  "Callahan", "Emmaline", "Jaxxon", "Margot", "Ryan", "Aryan", "Eden", "Rafael", "Summer",
  "Brantley", "Bianca", "Reece", "Esme", "Kabir", "Kira", "Russell", "Antonella", "Caden",
  "Adalee", "Francisco", "Laura", "Watson", "Zaylee", "Mauricio", "Maxine", "Keanu",
  "Camille", "Esteban", "Gabriela", "Owen", "Jayla", "Mckenzie", "Elaine", "Blaise",
  "Andi", "Shepherd", "Gianna", "Dante", "Gwen", "Marcellus", "Ivanna", "Wallace",
  "Spencer", "Maci", "Willie", "Luisa", "Maverick", "Kamari", "Terrance", "Anya", "Mercy",
  "Chelsea", "Kairo", "Judith", "Trinity", "Mark", "Taylor", "Chloe", "Aldo", "Nicole",
  "Bowen", "Yamileth", "Banks", "Esther", "Reina", "Caspian", "Aliana", "Aviana", "Elias",
  "Itzayana", "Reese", "Brixton", "Journee", "Princeton", "Itzel", "Desmond", "Rylie",
  "Arjun", "Elena", "Max", "Anastasia", "Cillian", "Presley", "Yahir", "Roselyn", "Victor",
  "Delaney", "Kareem", "Cameron", "Hadassah", "Jovanni", "Alexia", "Vincenzo", "Sevyn",
  "Colter", "Mariam", "Omar", "Averi", "Kye", "Everly", "Isla", "Leonardo", "Anahi",
  "Cassius", "Penelope", "Castiel", "Teresa", "Brycen", "Aria", "Gianni", "Leslie",
  "Cason", "Fernanda", "Jacob", "Veda", "Mack", "Yaretzi", "Niklaus", "Bellamy", "Zoey",
  "Jericho", "Autumn", "Rhys", "Salem", "Ty", "Abby", "Landry", "Benson", "Melody",
  "Cruz", "Laney", "Bentley", "Kalani", "Dawson", "Sutton", "Marceline", "Drew", "Kyro",
  "Evelyn", "Rodney", "Blaire", "Demetrius", "Adrianna", "Diego", "Faye", "Skyla", "Heath",
  "Hadleigh", "Cesar", "Keyla", "Opal", "Crew", "Sophie", "Jaxx", "Zhuri", "Bodhi",
  "Fox", "Vada", "Sergio", "Gia", "Seven", "Emmeline", "Daniel", "Jenna", "Jason",
  "Valeria", "Tommy", "Stephen", "Edward", "Keilani", "Elliott", "Aliya", "Austin",
  "Paislee", "Sage", "Juliet", "Foster", "Lexie", "Remy", "Ridge", "Madelynn", "Aron",
  "Adalyn", "Dalton", "Khalani", "Grady", "Paloma", "Zoe", "Wes", "Ivory", "Parker",
  "Skylar", "Alden", "Paul", "Tristen", "Giavanna", "Milan", "Charley", "Saul", "Meadow",
  "Khalil", "Rosa", "Beckett", "Aubriella", "Giuliana", "Abner", "Kadence", "Marley",
  "Nayeli", "Dario", "Elora", "Kason", "Malayah", "Brett", "Barbara", "Marvin", "Beatrice",
  "Olive", "Magnus", "Macie", "Kaiden", "Gracelyn", "Royal", "Tanner", "Eve", "Hank",
  "Aniya", "Eliel", "Andy", "Melissa", "Khari", "Zora", "Kennedi", "Samir", "Claire",
  "Kobe", "Alicia", "Zaiden", "Chana", "Bridger", "Mara", "Roberto", "Cora", "Cairo",
  "Kamden", "Sylvia", "Quincy", "Liv", "Eduardo", "Chaya", "Braxton", "Josue", "Selene",
  "Blaze", "Malcolm", "Laurel", "Phoebe", "Winnie", "Anakin", "Oaklyn", "Benjamin",
  "Chance", "Fallon", "Alvaro", "Jaylee", "Ryann", "Joe", "Elle", "Jaiden", "Elijah",
  "Brooklynn", "Zion", "Brynn", "Karson", "Jazmin", "Lyric", "Dominik", "Heaven", "Julio",
  "Kenia", "Forest", "Jabari", "Harper", "Kyler", "Rylee", "Salvador", "Adeline", "Hadlee",
  "Isaac", "Stevie", "Jade", "Journi", "Lawson", "Hayley", "Fabian", "Briella", "Crosby",
  "Alaya", "Everlee", "Mccoy", "Sean", "Malia", "Milani", "Talon", "Bexley", "Alice",
  "Evie", "Case", "Roy", "Cyrus", "Mekhi", "Aya", "Annabelle", "Fernando", "Emery",
  "Lila", "Dorian", "Omari", "Nora", "Paola", "Marianna", "Adler", "Jaylin", "Reuben",
  "Harley", "Ali", "Hailey", "Ansley", "Kylie", "Maximus", "Blakely", "Dayton", "Hudson",
  "Clementine", "Stephanie", "Oakley", "Maeve", "Randy", "Boston", "Piper", "Abram",
  "Sloane", "Emanuel", "Genevieve", "Emir", "Harmony", "Ian", "Ember", "Matias", "Zaria",
  "Eli", "Mabel", "Gunner", "Mary", "Jay", "Azalea", "Emiliano", "Marlee", "Miller",
  "Alondra", "Raylan", "Oakleigh", "Reginald", "Anne", "Leonidas", "Yareli", "Ayden",
  "Angelo", "Jakari", "Jaylah", "Jamie", "Bronson", "Avalynn", "Audrey", "Sawyer",
  "Remington", "Maximiliano", "Christina", "Rogelio", "Casey", "Misael", "Madalynn",
  "Felipe", "Miracle", "Marcelo", "Nova", "Eliza", "Ameer", "Jessie", "Miranda", "Zain",
  "Mazikee", "Leighton", "Kailey", "Kingsley", "Pearl", "Amari", "Riley", "Leif", "Layne",
  "Terry", "Wren", "Ledger", "Danna", "Hakeem", "Zara", "Amelie", "Noe", "Eleanor",
  "Cullen", "Janelle", "Memphis", "Ayaan", "Denisse", "Ezra", "Jesse", "Wade", "Carolyn",
  "Forrest", "Colton", "Grant", "Isabella", "Felix", "Raina", "Josiah", "Devin", "Nola",
  "Harlow", "Bryan", "Aniyah", "Leo", "Alivia", "Bailey", "Violet", "Harris", "Sienna",
  "Nash", "Indie", "Aaron", "Aubrie", "Colson", "June", "Dexter", "Brodie", "Etta",
  "Ariel", "Estella", "Zyaire", "Angelina", "Cristian", "Linda", "Eithan", "Leilany",
  "Karter", "Ivy", "Noel", "Madeline", "Gerardo", "Tiana", "Ander", "Marleigh", "Blake",
  "Kimberly", "Byron", "Hana", "Baker", "Iyla", "Korbin", "Alaia", "Wynter", "Rylan",
  "Raya", "Porter", "Kaiya", "Zechariah", "Sariyah", "Orlando", "Lilianna", "Jasiah",
  "Lucille", "Judson", "Moises", "Skyler", "Scarlette", "Atlas", "Gwendolyn", "Helena",
  "Rosalee", "Gabrielle", "Angel", "Belle", "Jagger", "Holden", "Saint", "Katelyn",
  "Lorenzo", "Addilyn", "Douglas", "Kennedy", "Emmett", "Juliana", "Alonzo", "Dilan",
  "Sky", "Paulina", "Luna", "Zola", "Kalel", "Anna", "Jayson", "Kaitlyn", "Curtis",
  "Brandon", "Charlie", "Alan", "Irene", "Tripp", "Scarlett", "Zev", "Matteo", "Niko",
  "Brittany", "Yusuf", "Kaden", "Aurora", "Clyde", "Cheyenne", "Brooks", "Samara",
  "Aurelia", "Lucca", "Jakob", "Aarya", "Madisyn", "Luca", "Lincoln", "Catherine", "Dulce",
  "Xiomara", "Valery", "Flynn", "Kaleb", "Mallory", "Maleah", "Oaklynn", "Ira",
];

const lastNames = [
  "Hurley", "Horton", "Griffith", "Stafford", "Leon", "Schmitt", "Stevens", "Curtis",
  "McDaniel", "Patton", "Cobb", "Shaw", "Reed", "Kemp", "Schneider", "Fuentes", "Camacho",
  "Pena", "Dalton", "Rasmussen", "Whitney", "David", "Nava", "Burnett", "McIntosh", "Day",
  "Bartlett", "Ho", "Madden", "Benton", "Wiggins", "Zimmerman", "Hart", "McBride", "Duffy",
  "Cox", "Patterson", "Spears", "Lowe", "Singh", "Roberson", "Bullock", "Pierce", "Chang",
  "Burton", "Carson", "Jackson", "Costa", "Villanueva", "Johns", "Owens", "Carpenter",
  "Ballard", "Casey", "Hale", "Francis", "Alexander", "Hendricks", "Waters", "Proctor",
  "Weaver", "Wise", "Walter", "Boyd", "Leonard", "Campos", "Mahoney", "Rollins", "Guerrero",
  "Mercado", "Merritt", "Stuart", "Howell", "Weeks", "Lewis", "McCoy", "Page", "Morse",
  "Sosa", "Berry", "Keith", "Holland", "Stewart", "Moreno", "Mejia", "Nguyen", "Compton",
  "Short", "Logan", "Bailey", "Heath", "Olson", "Esparza", "Wilkerson", "Ryan", "Harper",
  "Sims", "Myers", "Osborne", "Crawford", "Durham", "Cervantes", "Bradshaw", "Hess",
  "Bean", "Rice", "Farrell", "Villalobos", "Richmond", "Davis", "Castro", "Phillips",
  "Mullen", "Roth", "Barker", "Nielsen", "Delgado", "Flowers", "Zuniga", "Trevino",
  "Dejesus", "Harrington", "Hammond", "Leach", "King", "Pruitt", "Park", "Gonzales",
  "Kirk", "Guzman", "Baxter", "Snow", "Barnes", "Johnson", "Sweeney", "Arroyo", "Russell",
  "Payne", "Gibson", "Mata", "Houston", "Reyna", "Marquez", "Richard", "Grant", "Rosas",
  "Person", "Franco", "Greene", "Maldonado", "Vargas", "Nicholson", "Simon", "Lu",
  "Wilkinson", "Noble", "Mathis", "Poole", "Trujillo", "Fernandez", "Porter", "Garza",
  "Daugherty", "Benson", "Wolfe", "Ortiz", "Chambers", "Ramsey", "Farley", "Orr",
  "Schwartz", "Swanson", "Hogan", "Barrett", "Peters", "Peterson", "Graham", "Sanders",
  "Pace", "Kelley", "Deleon", "Bonilla", "Cohen", "Macias", "Parks", "Frazier", "Brown",
  "Cain", "Herman", "Tanner", "Cabrera", "Jordan", "Rose", "Buck", "Santana", "Snyder",
  "Jarvis", "Strong", "Kane", "Yu", "Wall", "Hood", "Sandoval", "Stout", "McPherson",
  "Lowery", "Cruz", "Buckley", "Larson", "Henry", "Moss", "Underwood", "Velasquez", "Hahn",
  "McCarthy", "Pham", "Bautista", "Nunez", "Hurst", "Bowman", "Becker", "Carey", "Foley",
  "Boone", "Vance", "Orozco", "Oliver", "Mack", "Hopkins", "Perez", "Davidson", "Moody",
  "McCarty", "Hull", "Lopez", "Blackwell", "Whitaker", "Portillo", "Figueroa", "Fischer",
  "Travis", "Branch", "Carter", "Krueger", "Church", "Barron", "Sellers", "Allison",
  "Garrett", "Truong", "Richards", "George", "Gordon", "Clark", "Marin", "Harvey",
  "Cantrell", "Cortes", "Tucker", "Greer", "Roach", "Clay", "Evans", "Nolan", "Woods",
  "Vazquez", "O'Connor", "Beil", "Steele", "Ali", "Diaz", "Wells", "Simpson", "Spence",
  "Armstrong", "Mayer", "Montes", "Hawkins", "Velez", "Murphy", "Rubio", "O'Connell",
  "Preston", "Kline", "Dudley", "Austin", "Lester", "Ellison", "Nelson", "Baker",
  "Bennett", "Christian", "Jacobson", "Barton", "Harris", "Vaughan", "Guevara", "Larsen",
  "Sanchez", "Atkins", "Petersen", "Anderson", "Sheppard", "Glover", "Floyd", "Moses",
  "Henson", "Young", "Mayo", "Brooks", "Quinn", "Conley", "Ball", "Pugh", "Bell",
  "Brewer", "Phelps", "Dunn", "Holloway", "Sierra", "Velazquez", "Benjamin",
  "Rodriguez", "Felix", "Glenn", "Valentine", "Davenport", "West", "Arellano", "Kirby",
  "McCann", "Graves", "Quintero", "Dickerson", "Weber", "Howard", "Landry", "Hendrix",
  "Walsh", "Crane", "Hardin", "Beck", "Dodson", "Bernal", "Wilson", "Charles", "Hamilton",
  "Chen", "Barnett", "Barajas", "Boyle", "Ruiz", "Mann", "Garner", "Juarez", "Best",
  "Vaughn", "Skinner", "Farmer", "Prince", "Marshall", "Tate", "Ashley", "Daniel",
  "Avalos", "McConnell", "Green", "Collier", "Patel", "Morales", "Cisneros", "Carlson",
  "Crosby", "Lim", "Maxwell", "York", "Yates", "Harrell", "Saunders", "Hanson", "Meza",
  "Knight", "Michael", "Golden", "Archer", "Waller", "Cross", "Frost", "Bridges", "Haynes",
  "Peralta", "Dougherty", "Bernard", "Barrera", "Gentry", "McCormick", "Stanley",
  "Chandler", "Ayala", "Hodges", "Hampton", "Harding", "Shannon", "Aguirre", "Watts",
  "Choi", "Ventura", "Hartman", "Tapia", "Ortega", "Salas", "Esquivel", "Harmon",
  "Mendoza", "Norris", "Rowe", "Zavala", "Boyer", "Tran", "Reilly", "Reid", "Sloan",
  "Fitzpatrick", "Yang", "Dillon", "Lawson", "Cantu", "Olsen", "Miller", "Schroeder",
  "Lucas", "Conway", "Stephenson", "Baldwin", "Bishop", "Craig", "Atkinson", "Duke",
  "Booker", "Brock", "Quintana", "Gillespie", "Faulkner", "Martinez", "Valdez", "Jenkins",
  "Koch", "Jimenez", "Raymond", "Hill", "Robbins", "Long", "Humphrey", "Huffman",
  "Schultz", "McLean", "Gregory", "Bush", "Powers", "Lynch", "Gaines", "Conrad", "Ramos",
  "Wade", "Briggs", "Lyons", "Kent", "Fleming", "Matthews", "Bowers", "Robinson", "Coffey",
  "Corona", "Blanchard", "Bentley", "Little", "Watson", "Morrison", "Dixon", "Adams",
  "Massey", "McLaughlin", "Calderon", "Wagner", "Clayton", "Price", "Warren", "Dennis",
  "Hunt", "Robertson", "Chavez", "Daniels", "Lane", "Small", "Reyes", "Khan", "Pearson",
  "Fletcher", "Townsend", "Fitzgerald", "Rich", "Conner", "Jefferson", "McMillan",
  "Pennington", "Griffin", "Sullivan", "Avery", "Beasley", "Hutchinson", "Salgado",
  "Montgomery", "Randall", "Tang", "McGuire", "Middleton", "Lucero", "Solis", "Roy",
  "Romero", "Villegas", "Stokes", "Shah", "Eaton", "Randolph", "Galvan", "Meadows",
  "Riley", "Allen", "Haley", "Cano", "Terry", "Estes", "Carroll", "Garrison", "Cline",
  "Delacruz", "Huang", "Mays", "Carrillo", "Maynard", "Hubbard", "Fuller", "Rogers",
  "Johnston", "Roberts", "Brady", "Pineda", "Jacobs", "Douglas", "Scott", "Holmes",
  "Mason", "Watkins", "Woodard", "Walters", "Mills", "Shaffer", "McCullough", "Delarosa",
  "Warner", "Caldwell", "Frye", "Novak", "Lynn", "Frederick", "Walls", "Espinoza",
  "Malone", "Hickman", "Nichols", "McKinney", "Tyler", "Combs", "Ingram", "Lee", "Horne",
  "Black", "Estrada", "Hughes", "Holt", "Wilkins", "Dominguez", "Hensley", "Pope",
  "Potter", "McMahon", "Vang", "Gutierrez", "Knapp", "Flores", "Williamson", "Huerta",
  "Correa", "Lawrence", "Morton", "Rush", "Newman", "Chung", "Fox", "Berger", "Parrish",
  "Bradford", "McClain", "Elliott", "Schmidt",
];

export function generateUserId() {
  const first = firstNames[Math.floor(Math.random() * firstNames.length)];
  const last = lastNames[Math.floor(Math.random() * lastNames.length)];
  const ts = Date.now();
  const count = String(counter++ % 1000).padStart(3, '0');
  return `${first}_${last}_${ts}_${count}`;
}
